// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5CT8Jyo9mvPSJSMA67DPTPPsrP9z_D90',
    appId: '1:349312254099:android:ad34881c6817fed26d4d66',
    messagingSenderId: '349312254099',
    projectId: 'pathfinder-e7869',
    storageBucket: 'pathfinder-e7869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfK45eoS-d0pxOrR16USzPsEnmuG8OEaw',
    appId: '1:349312254099:ios:dc81cb68dcd7efdb6d4d66',
    messagingSenderId: '349312254099',
    projectId: 'pathfinder-e7869',
    storageBucket: 'pathfinder-e7869.firebasestorage.app',
    androidClientId:
        '349312254099-l88skd0f3a934sh3jlc91rot2meto3jq.apps.googleusercontent.com',
    iosClientId:
        '349312254099-11bvg1iia71plds3eqnjpq0uc5ebq4b1.apps.googleusercontent.com',
    iosBundleId: 'com.pushpikaanuradha.pathfinder',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIXM709MoJ92lVfOi5oZilaSluaAlOYnQ',
    appId: '1:349312254099:web:8bb392bbb7531da86d4d66',
    messagingSenderId: '349312254099',
    projectId: 'pathfinder-e7869',
    authDomain: 'pathfinder-e7869.firebaseapp.com',
    storageBucket: 'pathfinder-e7869.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIXM709MoJ92lVfOi5oZilaSluaAlOYnQ',
    appId: '1:349312254099:web:7b0f0a9b6fa4cb266d4d66',
    messagingSenderId: '349312254099',
    projectId: 'pathfinder-e7869',
    authDomain: 'pathfinder-e7869.firebaseapp.com',
    storageBucket: 'pathfinder-e7869.firebasestorage.app',
  );
}